# @package _global_

defaults:
  - /method/mlp_head_ensemble/default@_here_

model:
  base_model_name_or_path: Qwen/Qwen3-14B

trainer:
  learning_rate: 1e-3
  regularization_towards_initial_weights: 1
  center_rewards_coefficient: 0
