# @package _global_

defaults:
  - /method/mlp_head_ensemble/default@_here_

model:
  base_model_name_or_path: trl-internal-testing/tiny-Qwen2ForCausalLM-2.5
  head_hidden_dim: 16
  num_heads: 3

trainer:
  precompute_features: False
