defaults:
  - override job_logging: none  # Disable default logging setup
  - override hydra_logging: none  # Disable default logging setup

# Output directory, generated dynamically on each run
run:
  dir: ${paths.log_dir}/${task_name}/runs/${now:%Y%m%d}-${now:%H%M%S}
sweep:
  dir: ${paths.log_dir}/${task_name}/multiruns/${now:%Y%m%d}-${now:%H%M%S}
  subdir: ${hydra.job.num}

# Logging configuration
job_logging:
  handlers:
    file:
      # Incorporates fix from https://github.com/facebookresearch/hydra/pull/2242
      filename: ${hydra.runtime.output_dir}/job.log
