# @package _global_

defaults:
  - /method/lora_ensemble/default@_here_

model:
  base_model_name_or_path: Skywork/Skywork-Reward-V2-Qwen3-4B

trainer:
  regularization_towards_initial_weights: 0.01
  learning_rate: 1e-4
