# @package _global_

defaults:
  - /method/dpo_head_dropout_ensemble/default@_here_

model:
  base_model_name_or_path: Skywork/Skywork-Reward-V2-Qwen3-4B
  dropout: 0.05

trainer:
  beta: 0.01
  learning_rate: 1e-5
